---
title: Home
date: 2025-05-28
date-modified: 2025-09-21
description: "616c616e"
listing:
  contents: blog/posts
  type: grid
  grid-columns: 3
  sort: "date desc"       # Sort by title, which includes date prefix
  fields: [image, date, title, description, categories]
  date-format: short
  image-height: 200px
  image-placeholder: "/assets/images/blog_placeholder.png"
  max-items: 3
---

Hello there! Welcome to my corner of the internet, where I try post cool stuff I find
in my life, opinions, thoughts, and some stuff that interests me. With my belief in
free and open-source, all of the contents on this website are licensed under the [MIT
license](LICENSE.qmd) unless otherwise stated.

## About
I'm usually a person who stays silent, and observes. I like thinking about big
questions and trying to understand the world. When I'm not silently daydreaming,
I like to study advanced physics and mathematics on my own, as well as tinkering
with technology and hardware. 

If you'd describe me with one word, it'd probably be "nerd." Other than nerd behavior, I
like playing the string bass and piano, as well as [watching sunsets](stuffs/sunsets) and taking walks.
I love identifying wild native plants in the area while hiking as well.

<br />
<br />

## See my latest blog posts!