---
title: "15.5 Directional Derivatives and the Gradient"
date: 2025-11-04
tags: [calc3, notes]
description: "Notes taken from West Valley College's Math 004A class, credits to my professor Steve Blasberg"
---

**Gradient of a function $f(x, y)$:**
	The gradient of a 3d function reduces to a 2d vector
	$\nabla f(x, y) = \langle \frac{\partial f}{\partial x}, \frac{\partial f}{\partial y} \rangle$
*This gives the direction of steepest ascent, or maximum $dz$*
*The direction of maximum descent is the negative of this vector*

**Directional derivative of a function $f$ at $(x_1, y_1)$ towards $\langle x_2, y_2 \rangle$**
	Make sure to use the unit vector of the direction vector
	$\nabla f(x, y)(x_1, y_1) \cdot \langle x_2, y_2 \rangle$
*For direction of no change, the directional derivative = 0, which means the dot of gradient and direction vector = 0, which means just a vector orthogonal to the gradient vector*

**The gradient vector at $(x, y)$ is orthogonal to the derivative at the same point**
$\frac{dy}{dx} = -\frac{\frac{\partial}{\partial x}}{\frac{\partial}{\partial y}}$
$\nabla f = \langle \frac{\partial}{\partial x}, \frac{\partial}{\partial y} \rangle$
*happens to be the inverse negative of what would've been $dy$ and $dx$ for slope, $\frac{dy}{dx}$*
