---
title: "15.4 The Chain Rule"
date: 2025-11-04
tags: [calc3, notes]
description: "Notes taken from West Valley College's Math 004A class, credits to my professor Steve Blasberg"
---

*Pretty similar to normal chain rule*

## Partial Chain Rule
Let $f(x, y) = z$ be a function in terms of $x$ and $y$
Let $x$ be a function of $s$ and $t$
Let $y$ be a function of $s$ and $t$

Then, $\frac{\partial z}{\partial s}$ would be $\frac{\partial f}{\partial x}\frac{\partial x}{\partial s} + \frac{\partial f}{\partial y}\frac{\partial y}{\partial s}$ 
$\frac{\partial z}{\partial t}$ would be the same thing, but instead of the partials of $x$ and $y$ in relation to $s$, it would be in relation to $t$.

## Find $\frac{dy}{dx}$ when there's $z$
Let $z$ be a function of $x$ and $y$
Using the partials of $z$ in terms vof $x$ and $y$:
	$\frac{dy}{dx}$ would be $-\frac{\frac{\partial z}{\partial x}}{\frac{\partial z}{\partial y}}$or, $-\frac{f_x}{f_y}$

## Partial 2nd derivative Chain Rule
Let $z$ be a differentiable function of $x$ and $y$
Let $x$ and $y$ be differentiable functions of $s$ and $t$
Then:
	$\frac{\partial z}{\partial s}=\frac{\partial z}{\partial x}\frac{\partial x}{\partial s} + \frac{\partial z}{\partial y}\frac{\partial y}{\partial s}$
And:
	$\frac{\partial z}{\partial t}=\frac{\partial z}{\partial x}\frac{\partial x}{\partial t} + \frac{\partial z}{\partial y}\frac{\partial y}{\partial t}$
The second derivatives are $f_{ss}$, $f_{st}$, and $f_{tt}$
 From the previous formulas:
	$f_s = f_x x_s + f_y y_s$
	$f_t = f_x x_t + f_y y_t$
$f_{ss}$ would be
	$(f_x x_s + f_y y_s)_s$
	$= (f_x)_s x_s + f_x x_{ss} + (f_y)_s y_s + f_y y_{ss}$
	$\boxed{= (f_{xx}x_s + f_{xy}y_s)x_s + f_x x_{ss} + (f_{yx}x_s + f_{yy} y_s)y_s + f_y y_{ss}}$
You could simplify that, but the grouping makes sense. Simply find these and plug:
$f_x$
$f_{xy}$
$f_{xx}$
$f_y$
$f_{yx}$
$f_{yy}$
$x_s$
$x_{ss}$
$y_s$
$y_{ss}$
Deriving for $f_{st}$ or $f_{tt}$ would be a similar process