---
title: "Past Problems: 2025"
description: "My reasoning through past Putnam problems"
date: 2026-09-04
---


A1 - Prove that $gcd(2m_k + 1, 2n_k + 1) = 1$ for all positive integers $k$ but for a finite amount of $k$.
---

*Definitions:*

1.
$gcd(m_k, n_k) = 1$
2.
$\frac{m_k}{n_k} = \frac{2m_{k-1} + 1}{2n_{k-1} + 1}$
3.
$m_0, n_0 \in \mathbf{Z}^+$

The crux of the problem is to prove that $gcd(2m_k + 1, 2n_k + 1) \neq 1$ for only a finite amount of $k$

We may hypothesize (for the sake of contradiction) that the $gcd \neq 1$ for infinitely many $k$. Thus in an attempt to prove this, we can set up an inductive hypothesis that if $gcd(2m_k + 1, 2n_k + 1) \neq 1$, then for $k+1$ the $gcd$ is also not $1$. By dichotomy as well, $gcd \neq 1$ for infinitely many $k$'s XOR finitely many $k$'s.

We may

1. attempt to disprove the inductive hypothesis
2. attempt to disprove the inductive base case

However attempting to disprove the inductive base case would be trying to prove the nonexistence of a $gcd \neq 1$ which is stronger than simply proving the finiteness of $gcd \neq 1$, which I don't think the problem write would make us do. So we will attempt to disprove the inductive hypothesis, which proves the finiteness of $gcd \neq 1$.