---
title: "Intro to Calc III"
date: 2025-06-02
date-modified: 2025-11-04
---

## My Messy Notes

- [vector basics!](notes/vector_basics.qmd)
- [curvature and normal vectors](notes/curvature_and_normal_vectors.qmd)
- [graphs and level curves](notes/graphs_and_level_curves.qmd)
- [limits and continuity](notes/limits_and_continuity.qmd)
- [partial derivatives](notes/partial_derivatives.qmd)
- [chain rule](notes/the_chain_rule.qmd)
- [directional derivatives and gradient](notes/directional_derivatives_and_gradient.qmd)
- [tangent planes and linear approximation](notes/tangent_planes_and_linear_approximation.qmd)
- [optimizing multivariable functions](notes/optimizing_multivariable_functions.qmd)
- [lagrange multipliers](notes/lagrange_multipliers.qmd)

## Overview of Contents
1. Vectors and 3d Space \
	1.1 Vectors and Vector Fields \
	1.2 Lines and Planes \
	1.3 Parametric Functions and Curves \
	1.4 Surfaces \
	1.5 Coordinate Systems \
2. Differentiation \
	2.1 Partial Derivatives \
	2.2 Chain Rule \
	2.3 Gradient and Directional Derivatives \
	2.4 Curl and Divergence \
	2.5 Optimization \
3. Integration \
	3.1 Multiple Integrals \
	3.2 Jacobian \
	3.3 Line Integrals \
	3.4 Surface and Flux Integrals \
	3.5 Stoke's and Divergence Theorem \
	3.6 Green's Theorem

## Vectors and 3d Space

...

## Differentiation

...

## Integration

...