name: Deploy Quarto site to GitHub Pages

on:
  push:
    branches: [ main ]  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto Project
        run: quarto render

      - name: Copy .well-known to public
        run: cp -r .well-known public/

      - name: Copy _config.yml to public
        run: cp _config.yml public/

#       - name: Copy modules to public
#         run: cp -r modules public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
